package com.example.TPXProj;

public enum Skill {
    COMMUNICATION,
    INTERPERSONAL,
    CREATIVITY,
    LEADERSHIP,
    MENTORING,
    TRAINING,
    ORGANIZATION,
    PLANNING,
    PROBLEM_SOLVING,
    RELATIONSHIP_BUILDING,
    REPORTING,
    TEAMWORK,
    TIME_MANAGEMENT,
    TIMELINESS
}
