package com.example.TPXProj.services;

import com.example.TPXProj.models.DatabaseNonprofit;
import com.example.TPXProj.models.Nonprofit;
import com.example.TPXProj.parsers.NonprofitParser;
import com.example.TPXProj.processors.NonprofitProcessor;
import com.example.TPXProj.processors.VolunteerProcessor;
import com.example.TPXProj.repositories.DatabaseNonprofitRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import java.util.ArrayList;

/**
 * Service class that allows custom mappings to various addresses
 *
 * @author Caleb Warner
 */
@RestController
public class DatabaseService {
    // *************************************************************************
    // Fields
    // **************************************************************************
    /**
     * Reference to the database object that communicates with the ClearDB MySQL Database
     */
    @Autowired
    private DatabaseNonprofitRepository repository;


    // *************************************************************************
    // Public Methods
    // **************************************************************************
    /**
     * Maps the address /api/nonprofits to a plain json object returned by the database consisting of all
     * nonprofits stored in the database.
     *
     * @return All nonprofits in the database in JSON format
     */
    @GetMapping("/api/nonprofits")
    public Iterable<DatabaseNonprofit> apiFindAllNonProfits() {
        return repository.findAll();
    }


    /**
     * Maps the address /api/nonprofits/formatted to a plain text page consisting of all info bits of all nonprofits
     * in the database, separated by line returns.
     *
     * @return All nonprofits in the database in text format
     */
    @GetMapping("/api/nonprofits/formatted")
    public String printNonprofits() {
        ArrayList<Nonprofit> nonprofitArrayList = NonprofitParser.parseDatabase(repository.findAll());
        String output = "";
        for (Nonprofit nonprofit : nonprofitArrayList) {
            output += nonprofit.printNonprofit();
            output += "<br><br>";
        }

        return output;
    }

    /**
     * Takes the post request from the formString and uses VolunteerProcessor to return an html file of the
     * top 4 nonprofits produced by VolunteerProcessor
     *
     * @param formString String generated by html form; found in the post request
     * @return Filled in html volunteer-submit.html file with top 4 nonprofits
     */
    @PostMapping("/volunteer-submit.html")
    public String serviceVolunteer(@RequestBody String formString) {
        VolunteerProcessor vp = new VolunteerProcessor(formString);
        vp.rankNonprofits(repository);
        return vp.output();
    }

    @PostMapping("/nonprofit-submit.html")
    public String serviceNonprofit(@RequestBody String formString) {
        NonprofitProcessor np = new NonprofitProcessor(formString);
        if (np.saveNonprofit(repository)) {
            return np.output();
        }
        return "Could not submit nonprofit to database.";
    }
}
